name: Push to Blot
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: display variables
      env:
        BLOT_URL: ${{ secrets.BLOT_URL}}
      run: |
        git remote set-url blot $BLOT_URL
        git push -u blot master
